version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"         # host:container

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://localhost:5000/"
        REACT_APP_SOCKET_URL: "ws://localhost:5000/ws/"
    ports:
      - "3000:3000"
    depends_on:
      - backend