version: "3.1"

services:
  db:
    image: mysql:8.0.34
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: chess_engine_db
      MYSQL_USER: user
      MYSQL_PASSWORD: '1qAz$w2*f34fsd'
      MYSQL_ROOT_PASSWORD: 'uTnw0PIh65_!'
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 3s
      timeout: 30s
      retries: 30
    volumes:
      - db_data_storage:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: chess_engine_db
      DB_USER: root
      DB_PASS: 'uTnw0PIh65_!'
      DB_PORT: 3306
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8082
      LOG_LEVEL: info
      DEBUG_RELOAD: True
      SECRET_KEY: '8GmooiSZSKN6H0pglRNFYBk7IkeqBrqXbKc7XuvlW5A'
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app-network
    command: >
      /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8082"

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      REACT_APP_BACKEND_URL: 'http://localhost:8082/api/v1/'
      REACT_APP_SOCKET_URL: 'ws://localhost:8082/ws/'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend
    networks:
      - app-network

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      PMA_HOST: backend
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data_storage:

networks:
  app-network:
