version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: chess_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1y7og8B4
      MONGO_INITDB_DATABASE: chess_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://root:1y7og8B4@mongodb:27017
      - MongoDB__DatabaseName=chess_db
      - MongoDB__CollectionName=engine_configs
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://localhost:5000/"
        REACT_APP_SOCKET_URL: "ws://localhost:5000/ws/"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
