FROM python:3.10

RUN mkdir /code

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . .

RUN pip install alembic

COPY ./alembic.ini /code/alembic.ini
COPY ./core/migrations /code/core/migrations

# Remove alembic upgrade command from Dockerfile
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8082"]